[package]
name = "quickstatements"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
mediawiki = "0.1.11"
#mediawiki = { path = "../mediawiki" }

wikibase = "0.3.4"
#wikibase = { path = "../wikibase_rs" }

mysql = { version="16.0.2" , features = ["ssl"] }
serde_json = "1"
config = "0.9.2"
regex = "1"
lazy_static = "1.3.0"
chrono = "0.4.6"
